# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "wazzuh" do |my_machine|
    config.vm.box = "ubuntu/focal64"
    #config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "wazzuh"
    config.vm.network "private_network", virtualbox__intnet: "servers", type: "static", ip: "172.30.0.66"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "ca_d_wazzuh"
      vb.memory = "2048"
      vb.cpus = "1"
      vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    end
  end
end
